export enum UserRole {
  STUDENT = 'STUDENT',
  COUNSELLOR = 'COUNSELLOR',
  ADMIN = 'ADMIN',
}

export enum AdminType {
  OWNER_ADMIN = 'OWNER_ADMIN',
  ADMIN = 'ADMIN',
}

export enum LeadSource {
  WEBSITE = 'WEBSITE',
  INSTAGRAM = 'INSTAGRAM',
  FACEBOOK = 'FACEBOOK',
  REFERRAL = 'REFERRAL',
  WALK_IN = 'WALK_IN',
  EVENTS = 'EVENTS',
  MANUAL = 'MANUAL',
  OTHER = 'OTHER',
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  COUNSELLING_SCHEDULED = 'COUNSELLING_SCHEDULED',
  COUNSELLING_COMPLETED = 'COUNSELLING_COMPLETED',
  INTERESTED = 'INTERESTED',
  NOT_INTERESTED = 'NOT_INTERESTED',
  CLOSED_LOST = 'CLOSED_LOST',
}

export enum StudentStage {
  LEAD_CAPTURED = 'LEAD_CAPTURED',
  PRELIMINARY_COUNSELLING = 'PRELIMINARY_COUNSELLING',
  PROFILE_EVALUATION = 'PROFILE_EVALUATION',
  UNIVERSITY_SHORTLISTING = 'UNIVERSITY_SHORTLISTING',
  DOCUMENT_COLLECTION = 'DOCUMENT_COLLECTION',
  APPLICATION_SUBMISSION = 'APPLICATION_SUBMISSION',
  OFFER_MANAGEMENT = 'OFFER_MANAGEMENT',
  FEE_PAYMENT = 'FEE_PAYMENT',
  VISA_PROCESSING = 'VISA_PROCESSING',
  PRE_DEPARTURE = 'PRE_DEPARTURE',
  DEPARTURE = 'DEPARTURE',
  ARRIVAL_CONFIRMED = 'ARRIVAL_CONFIRMED',
}

export enum DocumentStatus {
  REQUESTED = 'REQUESTED',
  UPLOADED = 'UPLOADED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  REJECTED = 'REJECTED',
}

export enum OfferStatus {
  ISSUED = 'ISSUED',
  SIGNED_UPLOADED = 'SIGNED_UPLOADED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}

export enum PaymentStatus {
  REQUESTED = 'REQUESTED',
  PROOF_SUBMITTED = 'PROOF_SUBMITTED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum VisaStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum TravelItemStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  BLOCKED = 'BLOCKED',
}

export enum TaskType {
  FOLLOW_UP = 'FOLLOW_UP',
  DOCUMENT_REVIEW = 'DOCUMENT_REVIEW',
  APPLICATION_SUBMISSION = 'APPLICATION_SUBMISSION',
  PAYMENT_VERIFICATION = 'PAYMENT_VERIFICATION',
  VISA_FOLLOW_UP = 'VISA_FOLLOW_UP',
  OPERATIONAL = 'OPERATIONAL',
  CUSTOM = 'CUSTOM',
}
